// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace NativeApiBind
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "appsec_infra";



        [DllImport(__DllName, EntryPoint = "add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint add(nuint left, nuint right);


    }



}
